# Generated by Django 5.1.6 on 2025-05-18 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Samochod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=64)),
                ('rok', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Samochód',
                'verbose_name_plural': 'Samochody',
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=64, unique=True)),
                ('marka', models.CharField(max_length=64)),
                ('opis', models.TextField(default='')),
                ('data_produkcji', models.DateField(blank=True, null=True)),
                ('cena', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('zdjecie', models.ImageField(blank=True, null=True, upload_to='parts/')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('samochody', models.ManyToManyField(blank=True, to='parts.samochod')),
            ],
        ),
        migrations.CreateModel(
            name='PartDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod_producenta', models.CharField(max_length=32)),
                ('kraj_produkcji', models.CharField(max_length=64)),
                ('part', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parts.part')),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(blank=True, max_length=100)),
                ('nazwisko', models.CharField(blank=True, max_length=100)),
                ('opis', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatary/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ocena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocena', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('komentarz', models.TextField(blank=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.part')),
            ],
            options={
                'unique_together': {('part', 'autor')},
            },
        ),
    ]
